"""
Extract Business Failure Data for Heatmap Visualization
========================================================

This script extracts all business failures from the main dataset
and prepares them for interactive heatmap visualization.

Output: JSON data embedded in HTML file
"""

import pandas as pd
import json
from pathlib import Path
import sys

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')
    sys.stderr.reconfigure(encoding='utf-8')

print("="*80)
print("EXTRACTING BUSINESS FAILURE DATA FOR HEATMAP")
print("="*80)
print()

# ============================================================================
# Load Data
# ============================================================================

print("Loading dataset...")
DATA_PATH = Path("outputs/kaggle_clean_data/jakarta_clean_categorized.csv")
df = pd.read_csv(DATA_PATH)

print(f"✓ Total POIs: {len(df):,}")
print()

# ============================================================================
# Filter Failures
# ============================================================================

print("Filtering failures (closed businesses)...")
failures = df[df['date_closed'].notna()].copy()

print(f"✓ Total failures: {len(failures):,} ({len(failures)/len(df)*100:.2f}%)")
print()

# ============================================================================
# Statistics by Category
# ============================================================================

print("Calculating statistics by category...")
print()

category_stats = failures['poi_type'].value_counts().head(15)

print("Top 15 POI Categories by Failure Count:")
print("-" * 60)
for category, count in category_stats.items():
    total_in_category = len(df[df['poi_type'] == category])
    failure_rate = count / total_in_category * 100 if total_in_category > 0 else 0
    print(f"{category:20s}: {count:5,} failures ({failure_rate:5.2f}% rate)")

print()

# ============================================================================
# Extract Coordinates by Category
# ============================================================================

print("Extracting coordinates by category...")

# Get top categories
top_categories = category_stats.head(15).index.tolist()

heatmap_data = {}
category_info = {}

for category in top_categories:
    cat_failures = failures[failures['poi_type'] == category]

    # Extract coordinates [lat, lon] format for Leaflet.heat
    coords = cat_failures[['latitude', 'longitude']].values.tolist()

    heatmap_data[category] = coords

    # Calculate statistics
    total_in_cat = len(df[df['poi_type'] == category])
    failure_count = len(cat_failures)
    failure_rate = failure_count / total_in_cat * 100 if total_in_cat > 0 else 0

    category_info[category] = {
        'count': failure_count,
        'total': total_in_cat,
        'rate': round(failure_rate, 2)
    }

    print(f"  ✓ {category}: {len(coords):,} points")

print()

# ============================================================================
# Statistics by Regency
# ============================================================================

print("Statistics by Regency:")
print("-" * 60)

regency_stats = failures['regency'].value_counts()
for regency, count in regency_stats.items():
    total_in_regency = len(df[df['regency'] == regency])
    failure_rate = count / total_in_regency * 100 if total_in_regency > 0 else 0
    print(f"{regency:20s}: {count:5,} failures ({failure_rate:5.2f}% rate)")

print()

# ============================================================================
# Export Data
# ============================================================================

print("Preparing data for export...")

# Combine all data
export_data = {
    'heatmap_data': heatmap_data,
    'category_info': category_info,
    'statistics': {
        'total_pois': len(df),
        'total_failures': len(failures),
        'failure_rate': round(len(failures) / len(df) * 100, 2),
        'categories': len(heatmap_data),
        'regencies': regency_stats.to_dict()
    }
}

# Save as JSON for inspection
output_json = Path("outputs/visualizations/failure_data.json")
with open(output_json, 'w', encoding='utf-8') as f:
    json.dump(export_data, f, indent=2)

print(f"✓ Saved JSON data: {output_json}")
print(f"  File size: {output_json.stat().st_size / 1024 / 1024:.2f} MB")

# Create JavaScript variable for embedding in HTML
js_output = Path("outputs/visualizations/failure_data.js")
with open(js_output, 'w', encoding='utf-8') as f:
    f.write("// Business Failure Data for Heatmap\n")
    f.write("// Auto-generated by extract_failure_data.py\n\n")
    f.write(f"const failureData = {json.dumps(export_data, indent=2)};\n")

print(f"✓ Saved JS data: {js_output}")
print()

# ============================================================================
# Summary
# ============================================================================

print("="*80)
print("DATA EXTRACTION COMPLETE!")
print("="*80)
print()
print(f"Total failures extracted: {len(failures):,}")
print(f"Categories: {len(heatmap_data)}")
print(f"Total data points: {sum(len(v) for v in heatmap_data.values()):,}")
print()
print("Top 5 Categories by Failure Count:")
for i, (category, count) in enumerate(category_stats.head(5).items(), 1):
    print(f"  {i}. {category}: {count:,} failures")
print()
print("Output files:")
print(f"  1. {output_json}")
print(f"  2. {js_output}")
print()
print("Ready to create HTML heatmap!")
print("="*80)
